// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TiptapController from "./tiptap_controller"
application.register("tiptap", TiptapController)

import MermaidController from "./mermaid_controller"
application.register("mermaid", MermaidController)

import KanbanController from "./kanban_controller"
application.register("kanban", KanbanController)
